### ISSUE TITLE
处理带划痕的是什么命令，我这为啥报错

### ISSUE THREAD

**Issue by linyangch** [2424004764/old_photos_reappear_brilliance#3]
大佬，带划痕的怎么不行，最后没生成图片。不带划痕的是正常的。
是我这命令不对吗？就把test_images/old换成test_images/old_w_scratch，加了个 --with_scratch。
GPU那用改代码吗，还是文件夹路径没弄对

root@f917cf5388bc:/usr/yifang/photo_restoration# python3.8 run.py --input_folder /usr/yifang/photo_restoration/test_images/old_w_scratch --output_folder /usr/yifang/photo_restoration/output --GPU -1 --with_scratch

Running Stage 1: Overall restoration
initializing the dataloader
/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
model weights loaded
Traceback (most recent call last):
  File "detection.py", line 155, in <module>
    main(config)
  File "detection.py", line 80, in main
    model.to(config.GPU)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 600, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)

RuntimeError: Device index must not be negative

You are using NL + Res
Traceback (most recent call last):
  File "test.py", line 110, in <module>
    input_loader = os.listdir(opt.test_input)

FileNotFoundError: [Errno 2] No such file or directory: '/usr/yifang/photo_restoration/output/stage_1_restore_output/masks/input'

Finish Stage 1 ...

**Comment by 2424004764** [comment]
这个我也没遇到过    可以关注下微软他们的关于这个问题的issue https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues?q=is%3Aissue+is%3Aopen+with_scratch

**Comment by linyangch** [comment]
> 这个我也没遇到过 可以关注下微软他们的关于这个问题的issue https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues?q=is%3Aissue+is%3Aopen+with_scratch

这个内存占用真是个问题，我这还没GPU，，，你自己用的时候，处理带折痕图像是正常的吗？用GPU了吗，内存多大的

**Comment by 2424004764** [comment]
这个命令我没用过
